name: Publish

on:
    push:
        branches:
            - main

jobs:
    publish:
        # To enable auto publishing to github, update your electron publisher
        # config in package.json > "build" and remove the conditional below

        runs-on: ${{ matrix.os }}

        strategy:
            matrix:
                os: [macos-latest]

        steps:
            - name: Checkout git repo
              uses: actions/checkout@v3

            - name: Install Node and NPM
              uses: actions/setup-node@v3
              with:
                  node-version: 16
                  cache: npm

            - name: Install and build
              run: |
                  # cat > .env <<EOF
                  #     MONGODB_URI=${{ secrets.MONGODB_URI }}
                  #     GH_TOKEN=${{ secrets.GH_TOKEN }}
                  # EOF
                  npm install
                  npm run postinstall
                  npm run build

            - name: Publish releases
              env:
                  # These values are used for auto updates signing
                  APPLE_ID: ${{ secrets.APPLE_ID }}
                  APPLE_ID_PASS: ${{ secrets.APPLE_ID_PASS }}
                  CSC_LINK: ${{ secrets.CSC_LINK }}
                  CSC_KEY_PASSWORD: ${{ secrets.CSC_KEY_PASSWORD }}
                  WIN_CSC_LINK: ${{ secrets.WIN_CSC_LINK }}
                  WIN_CSC_KEY_PASSWORD: ${{secrets.WIN_CSC_KEY_PASSWORD}}
                  # CSC_INSTALLER_LINK: ${{ secrets.CSC_INSTALLER_LINK }}
                  # CSC_INSTALLER_KEY_PASSWORD: ${{ secrets.CSC_INSTALLER_KEY_PASSWORD }}
                  # This is used for uploading release assets to github
                  GH_TOKEN: ${{ secrets.GH_TOKEN }} # add repo full scope
              run: |
                  npm exec electron-builder -- --publish always --win --mac --linux
